// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDMAHT2qJlgoMOKy8UBM1tVYP2-qzMww',
    appId: '1:388501237026:web:0160794862dff760f6097b',
    messagingSenderId: '388501237026',
    projectId: 'faiju-fire-d6e45',
    authDomain: 'faiju-fire-d6e45.firebaseapp.com',
    storageBucket: 'faiju-fire-d6e45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJjWHYY9lc8DJqdUJS6nFCObBJ7UJB2E',
    appId: '1:388501237026:android:ce94c279006fcc04f6097b',
    messagingSenderId: '388501237026',
    projectId: 'faiju-fire-d6e45',
    storageBucket: 'faiju-fire-d6e45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NGIsJgGwVFdmzAZb8a8ODZg7FSnqhQQ',
    appId: '1:388501237026:ios:d75f6620c48c3029f6097b',
    messagingSenderId: '388501237026',
    projectId: 'faiju-fire-d6e45',
    storageBucket: 'faiju-fire-d6e45.appspot.com',
    iosBundleId: 'com.example.faijuFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NGIsJgGwVFdmzAZb8a8ODZg7FSnqhQQ',
    appId: '1:388501237026:ios:d75f6620c48c3029f6097b',
    messagingSenderId: '388501237026',
    projectId: 'faiju-fire-d6e45',
    storageBucket: 'faiju-fire-d6e45.appspot.com',
    iosBundleId: 'com.example.faijuFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzDMAHT2qJlgoMOKy8UBM1tVYP2-qzMww',
    appId: '1:388501237026:web:f07a0b1d0b17d469f6097b',
    messagingSenderId: '388501237026',
    projectId: 'faiju-fire-d6e45',
    authDomain: 'faiju-fire-d6e45.firebaseapp.com',
    storageBucket: 'faiju-fire-d6e45.appspot.com',
  );
}
